set nocompatible
filetype off

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" Vundle 
Bundle 'vim-scripts/bufkill.vim'
Bundle 'vim-scripts/YankRing.vim'
Bundle 'godlygeek/csapprox'
" Bundle 'flazz/vim-colorschemes'
Bundle 'gmarik/vundle'
Bundle 'kien/ctrlp.vim'
Bundle 'tpope/vim-fugitive'
Bundle 'mileszs/ack.vim'
Bundle 'scrooloose/syntastic'
Bundle 'scrooloose/nerdcommenter'
Bundle 'majutsushi/tagbar'
Bundle 'tsaleh/vim-supertab'
Bundle 'shawncplus/phpcomplete.vim'


" General 
filetype plugin indent on 
syntax enable 
colorscheme darkspectrum 
set number
let mapleader = ","
set nowrap
set clipboard=unnamed
set modifiable

" Highlight column 80
highlight ColorColumn ctermbg=black guibg=black
set colorcolumn=80
" Run phpunit for current file
au FileType php nnoremap <leader>ua <esc>:!phpunit %:p:.<cr>

" Run phpunit for function name under cursor
au FileType php nnoremap <leader>uf <esc>:!phpunit --filter <cword> %:p:.<cr>

" Edit & source .vimrc
nnoremap <leader>ev :vsplit $MYVIMRC<cr>
nnoremap <leader>sv :source $MYVIMRC<cr>

" Use ctrl-[hjkl] to select the active split!
nnoremap <c-h> <c-w>h
nnoremap <c-l> <c-w>l
nnoremap <c-j> <c-w>j
nnoremap <c-k> <c-w>k

" Default tabbing is 4 spaces
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

" Start moving vertically 7 lines away from top or bottom
set so=7

" Allow backspace to delete indent, eol, start
set bs=2

" Ctrl p caching
let g:ctrlp_use_caching = 1 


" Show file info in terminal window
set title

" Incremental search
set incsearch

" Highlight search results
set hlsearch

" highlight matching (,{ 
set showmatch

" Remove highlight
nnoremap <leader><esc> :noh<return><esc>

" yank ring mappings 
let g:yankring_replace_n_pkey = '<leader>m'
let g:yankring_replace_n_nkey = '<leader>n'
let g:yankring_history_dir = '~/.vim/tmp'
nmap <silent> <leader>yr :YRShow<cr>

"  w!! to write a file as sudo
cmap w!! w !sudo tee % >/dev/null

" splits ,v and ,h to open new splits (vertical and horizontal)
nnoremap <leader>v <C-w>v<C-w>l
nnoremap <leader>h <C-w>s<C-w>j

" map tagbar toggle
nnoremap <leader>t :TagbarToggle<CR>
let g:tagbar_autoclose = 1

" add space when comenting out with nerd comment
let NERDSpaceDelims = 1

" allow p to paste from system clipboard
noremap p "+p

" omni complete and supertab
" set ofu=syntaxcomplete#Complete
" let g:SuperTabDefaultCompletionType = "<C-X><C-O>"
let g:SuperTabDefaultCompletionType = "context"

" allow mouse to be used
set mouse=a
